// Mocks generated by Mockito 5.4.6 from annotations
// in vronmobile2/test/features/scanning/services/combined_scan_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:io' as _i8;

import 'package:http/http.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:vronmobile2/features/scanning/models/scan_data.dart' as _i5;
import 'package:vronmobile2/features/scanning/services/blenderapi_service.dart'
    as _i7;
import 'package:vronmobile2/features/scanning/services/usdz_combiner_service.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeClient_0 extends _i1.SmartFake implements _i2.Client {
  _FakeClient_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [USDZCombinerService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUSDZCombinerService extends _i1.Mock
    implements _i3.USDZCombinerService {
  MockUSDZCombinerService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<String> combineScans({
    required List<_i5.ScanData>? scans,
    required String? outputPath,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#combineScans, [], {
              #scans: scans,
              #outputPath: outputPath,
            }),
            returnValue: _i4.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#combineScans, [], {
                  #scans: scans,
                  #outputPath: outputPath,
                }),
              ),
            ),
          )
          as _i4.Future<String>);
}

/// A class which mocks [BlenderAPIService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBlenderAPIService extends _i1.Mock implements _i7.BlenderAPIService {
  MockBlenderAPIService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseUrl =>
      (super.noSuchMethod(
            Invocation.getter(#baseUrl),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#baseUrl),
            ),
          )
          as String);

  @override
  String get apiKey =>
      (super.noSuchMethod(
            Invocation.getter(#apiKey),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#apiKey),
            ),
          )
          as String);

  @override
  _i2.Client get client =>
      (super.noSuchMethod(
            Invocation.getter(#client),
            returnValue: _FakeClient_0(this, Invocation.getter(#client)),
          )
          as _i2.Client);

  @override
  _i4.Future<String> createSession() =>
      (super.noSuchMethod(
            Invocation.method(#createSession, []),
            returnValue: _i4.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#createSession, []),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<void> uploadGLB({
    required String? sessionId,
    required _i8.File? glbFile,
    void Function(double)? onProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#uploadGLB, [], {
              #sessionId: sessionId,
              #glbFile: glbFile,
              #onProgress: onProgress,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> startNavMeshGeneration({
    required String? sessionId,
    required String? inputFilename,
    required String? outputFilename,
    Map<String, dynamic>? navmeshParams,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#startNavMeshGeneration, [], {
              #sessionId: sessionId,
              #inputFilename: inputFilename,
              #outputFilename: outputFilename,
              #navmeshParams: navmeshParams,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String> pollStatus({
    required String? sessionId,
    Duration? pollingInterval,
    int? maxAttempts,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#pollStatus, [], {
              #sessionId: sessionId,
              #pollingInterval: pollingInterval,
              #maxAttempts: maxAttempts,
            }),
            returnValue: _i4.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#pollStatus, [], {
                  #sessionId: sessionId,
                  #pollingInterval: pollingInterval,
                  #maxAttempts: maxAttempts,
                }),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<void> downloadNavMesh({
    required String? sessionId,
    required String? filename,
    required String? outputPath,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#downloadNavMesh, [], {
              #sessionId: sessionId,
              #filename: filename,
              #outputPath: outputPath,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteSession({required String? sessionId}) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSession, [], {#sessionId: sessionId}),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String> generateNavMesh({
    required _i8.File? glbFile,
    required String? outputPath,
    void Function(double)? onProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#generateNavMesh, [], {
              #glbFile: glbFile,
              #outputPath: outputPath,
              #onProgress: onProgress,
            }),
            returnValue: _i4.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#generateNavMesh, [], {
                  #glbFile: glbFile,
                  #outputPath: outputPath,
                  #onProgress: onProgress,
                }),
              ),
            ),
          )
          as _i4.Future<String>);
}
