#!/bin/bash

# Generate build information for the app
# This script captures git commit info and environment details
# Output: lib/core/config/build_info.dart

set -e

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${GREEN}🔨 Generating build info...${NC}"

# Get build information
BUILD_TIME=$(date -u +"%Y-%m-%d %H:%M UTC")
COMMIT_HASH=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
COMMIT_MESSAGE=$(git log -1 --pretty=%B 2>/dev/null | head -n 1 || echo "No commit message")
BRANCH=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown")
ENVIRONMENT="${FLUTTER_ENV:-staging}"

# Sanitize commit message (escape quotes and newlines)
COMMIT_MESSAGE=$(echo "$COMMIT_MESSAGE" | sed 's/"/\\"/g' | tr '\n' ' ')

# Create output directory if it doesn't exist
OUTPUT_DIR="lib/core/config"
mkdir -p "$OUTPUT_DIR"

# Generate Dart file
OUTPUT_FILE="$OUTPUT_DIR/build_info.dart"

cat > "$OUTPUT_FILE" <<EOF
// GENERATED CODE - DO NOT EDIT
// Generated by scripts/generate_build_info.sh
// Build Time: $BUILD_TIME

/// Build information captured at compile time
class BuildInfo {
  /// When the app was built (UTC)
  static const String buildTime = '$BUILD_TIME';

  /// Git commit hash (short)
  static const String commitHash = '$COMMIT_HASH';

  /// Commit message (first line)
  static const String commitMessage = '''$COMMIT_MESSAGE''';

  /// Git branch name
  static const String branch = '$BRANCH';

  /// Environment (staging, production, development)
  static const String environment = '$ENVIRONMENT';

  /// Full version string
  static String get fullVersion => '\$commitHash on \$branch';

  /// Formatted build info for display
  static String get formattedInfo => '''
──────── Status ────────
Build Time:   \$buildTime
Commit:       \$commitHash
Message:      \$commitMessage
Branch:       \$branch
Environment:  \$environment
''';
}
EOF

echo -e "${GREEN}✓ Build info generated${NC}"
echo -e "${YELLOW}  Build Time: $BUILD_TIME${NC}"
echo -e "${YELLOW}  Commit:     $COMMIT_HASH${NC}"
echo -e "${YELLOW}  Branch:     $BRANCH${NC}"
echo -e "${YELLOW}  Environment: $ENVIRONMENT${NC}"
echo ""
